backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site_data"
    label: "Site Data"
    files:
      - label: "Main content (data.json)"
        name: "data"
        file: "content/data.json"
        fields:
          - {label: "Announcements", name: "announcements", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Date", name: "date", widget: "datetime", required: false},
              {label: "Body", name: "body", widget: "text"}
            ]}
          - {label: "Staff", name: "staff", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Role", name: "role", widget: "string"},
              {label: "Email", name: "email", widget: "string", required: false},
              {label: "Phone", name: "phone", widget: "string", required: false}
            ]}
          - {label: "Books", name: "books", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Author", name: "author", widget: "string", required: false},
              {label: "Category", name: "category", widget: "string", required: false},
              {label: "Year", name: "year", widget: "string", required: false}
            ]}
          - {label: "E-Resources", name: "eresources", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Link", name: "link", widget: "string"},
              {label: "Description", name: "description", widget: "text", required: false}
            ]}
